version: 1.1.{build}.0
image: Visual Studio 2017
build_script:
- ps: .\build.ps1 -configuration release
after_build:
- ps: |
    Invoke-WebRequest "https://downloads.vigem.org/other/pavel-a/ddverpatch/verpatch-1.0.15.1-x86-codeplex.zip" -OutFile verpatch-1.0.15.1-x86-codeplex.zip
    Expand-Archive verpatch-1.0.15.1-x86-codeplex.zip -DestinationPath .
    .\verpatch.exe .\bin\x64\Injector.exe "$env:APPVEYOR_BUILD_VERSION"
    .\verpatch.exe .\bin\x64\Injector.exe /pv "$env:APPVEYOR_BUILD_VERSION"
    .\verpatch.exe .\bin\Win32\Injector.exe "$env:APPVEYOR_BUILD_VERSION"
    .\verpatch.exe .\bin\Win32\Injector.exe /pv "$env:APPVEYOR_BUILD_VERSION"
artifacts:
- path: bin
  name: Injector_x86_amd64
deploy:
- provider: Environment
  name: BUILDBOT
  on:
    appveyor_repo_tag: true